# StarterKits configuration file.

# If kits will be distributed to players.  If false, kits will be disabled and players will not be flagged as having received a kit.
kits_enabled: false

# The actual kit.  Consists of a hyphenated list of items, which are pairs of item name and count.
kit:
  - name: WOODEN_PICKAXE
    count: 1
  - name: APPLE
    count: 5
  - name: ENDER_CHEST
    count: 1
  - name: RED_BED
    count: 1
  - name: COMPASS
    count: 1